#theme = "starlight"
theme = 'dark_plus'

[editor]
bufferline = "multiple"
auto-format = true
mouse = false
line-number = "relative"
end-of-line-diagnostics = 'hint'
popup-border = 'all'
scrolloff = 10
cursorline = true
auto-info = true

[editor.file-picker]
hidden = false # to show .hidden files

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false
display-messages = true

[editor.inline-diagnostics]
cursor-line = 'hint'
other-lines = "disable"

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[keys.normal]
a = ["append_mode", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
d = "delete_selection_noyank"
D = 'kill_to_line_end'
c = "change_selection_noyank"
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
L = "goto_line_end"
H = "goto_first_nonwhitespace"
C-s = ':w!'
y = [':clipboard-yank', 'yank']
C-v = [':clipboard-paste-before']
C-d = ["search_selection", "search_next"]
C-space = 'signature_help'
C-x = 'completion'

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"

[keys.normal.m]
# allow selecting inside next pair from outside
"\"" = "@f\";vmi\""
"'"  = "@f';vmi'"
"[" = "@f[;vmi]"
"(" = "@f(;vmi)"
"<"  = "@f<gt>;vmi<lt>"
"{" = "@f{;vmi}"

[keys.insert]
C-s = [':w!', 'normal_mode']
C-v = [':clipboard-paste-before']
C-space = 'signature_help'

[keys.select]
D = 'kill_to_line_end'
d = "delete_selection_noyank"
c = "change_selection_noyank"
y = [':clipboard-yank', 'yank']
";" = ["collapse_selection", "normal_mode"]
V = "extend_to_line_end"

