#theme = "starlight"
theme = 'dark_plus'

[editor]
bufferline = "multiple"
auto-format = true
mouse = false
line-number = "relative"
end-of-line-diagnostics = 'hint'
popup-border = 'all'
scrolloff = 10

[editor.file-picker]
hidden = false # to show .hidden files

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = 'hint'
other-lines = "disable"

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
d = "delete_selection_noyank"
D = 'kill_to_line_end'
c = "change_selection_noyank"
C-s = ':w!'
y = [':clipboard-yank', 'yank']
C-v = [':clipboard-paste-before']
C-d = ["search_selection", "search_next"]

[keys.insert]
C-s = [':w!', 'normal_mode']
C-v = [':clipboard-paste-before']

[keys.select]
D = 'kill_to_line_end'
d = "delete_selection_noyank"
c = "change_selection_noyank"
y = [':clipboard-yank', 'yank']
