[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
auto-format = true

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.basedpyright.analysis]
diagnosticMode = 'openFilesOnly'
typeCheckingMode = "standard"
autoImportCompletions = true
inlayHints.callArgumentNames = false

[language-server.ruff]
command = "ruff"
args = ["server"]
